title: fedora Stewardship SIG

description: >-
  The Stewardship SIG takes care of abandoned fedora packages.

url:            "https://fedora-stewardship.github.io"
baseurl:        ""

github_username: fedora-stewardship

markdown:       kramdown
theme:          minima
show_excerpts:  true

header_pages:
  - "_pages/news.md"
  - "_pages/sig-report.html"
  - "_pages/sig-overview.md"
  - "_pages/pr-report.md"
  - "_pages/sig-backlog.md"
  - "_pages/interna.md"

plugins:
  - jekyll-feed

include: ["_pages"]

exclude:
  - .compose
  - .git/
  - .idea/
  - .gitignore
  - data/
  - Gemfile
  - Gemfile.lock
  - README.md
  - scripts/
  - update
  - UNLICENSE
  - vendor/

